version: 2.1
parameters:
  param-string:
    type: string
    description: A test string value
    default: "test-string-value"
  param-bool:
    type: boolean
    description: A test of boolean values.
    default: false
  param-integer:
    description: A test of integer parameters
    type: integer
    default: -1
  param-enum:
    description: A test of enum parameters
    default: "foo"
    type: enum
    enum: ["foo", "bar", "car"]

jobs:
  parameter-build:
    docker:
      - image: circleci/python:3.8
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    environment:
      PARAM_STRING: << parameters.param-string >>
      PARAM_BOOL: << parameters.param-bool >>
    steps:
      - run: echo hi $PARAM_STRING - $PARAM_BOOL : << parameters.param-integer >> - << parameters.param-enum >>

workflows:
  doit:
    jobs:
      - parameter-build